import type { Metadata } from "next";
import "./globals.css";
import { Anybody, Raleway } from 'next/font/google'

const anybody = Anybody({ subsets: ['latin'], weight: ["700","400"] })
const raleway = Raleway({ subsets: ['latin'], weight: ["700"], variable: "--raleway"})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${anybody.className} ${raleway.variable}`}>
      {children}
      </body>
    </html>
  );
}
